import Quiz from "@/components/shared/Quiz";

type Props = { params: { quizId: string } };
const page = ({ params: { quizId } }: Props) => {
  return (
    <Quiz
      questionTitle=""
      subtitle=""
      quizId={quizId}
      questions={[
        {
          _id: "1",
          student: "student1",
          question: {
            _id: "q1",
            question: "What is 2 + 2?",
            options: [
              { name: "1", tag: "Incorrect", images: null, _id: "1_1" },
              { name: "2", tag: "Incorrect", images: null, _id: "1_2" },
              { name: "3", tag: "Incorrect", images: null, _id: "1_3" },
              { name: "4", tag: "Correct", images: null, _id: "1_4" },
            ],
            standard: 5,
            subject: "Mathematics",
            chapter: ["Arithmetic"],
            topics: ["Basic Operations"],
            subtopics: ["Addition"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "4",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "2",
          student: "student1",
          question: {
            _id: "q2",
            question: "What is the capital of France?",
            options: [
              { name: "Berlin", tag: "Incorrect", images: null, _id: "2_1" },
              { name: "London", tag: "Incorrect", images: null, _id: "2_2" },
              { name: "Paris", tag: "Correct", images: null, _id: "2_3" },
              { name: "Rome", tag: "Incorrect", images: null, _id: "2_4" },
            ],
            standard: 5,
            subject: "Geography",
            chapter: ["Capitals"],
            topics: ["Countries and Capitals"],
            subtopics: ["Europe"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "Paris",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "3",
          student: "student1",
          question: {
            _id: "q3",
            question: "What is 3 + 5?",
            options: [
              { name: "5", tag: "Incorrect", images: null, _id: "3_1" },
              { name: "8", tag: "Correct", images: null, _id: "3_2" },
              { name: "10", tag: "Incorrect", images: null, _id: "3_3" },
              { name: "12", tag: "Incorrect", images: null, _id: "3_4" },
            ],
            standard: 5,
            subject: "Mathematics",
            chapter: ["Arithmetic"],
            topics: ["Basic Operations"],
            subtopics: ["Addition"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "8",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "4",
          student: "student1",
          question: {
            _id: "q4",
            question: "What is the largest planet?",
            options: [
              { name: "Earth", tag: "Incorrect", images: null, _id: "4_1" },
              { name: "Mars", tag: "Incorrect", images: null, _id: "4_2" },
              { name: "Jupiter", tag: "Correct", images: null, _id: "4_3" },
              { name: "Saturn", tag: "Incorrect", images: null, _id: "4_4" },
            ],
            standard: 5,
            subject: "Science",
            chapter: ["Solar System"],
            topics: ["Planets"],
            subtopics: ["Largest Planets"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "Jupiter",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "5",
          student: "student1",
          question: {
            _id: "q5",
            question: "What is the smallest prime number?",
            options: [
              { name: "1", tag: "Incorrect", images: null, _id: "5_1" },
              { name: "2", tag: "Correct", images: null, _id: "5_2" },
              { name: "3", tag: "Incorrect", images: null, _id: "5_3" },
              { name: "4", tag: "Incorrect", images: null, _id: "5_4" },
            ],
            standard: 5,
            subject: "Mathematics",
            chapter: ["Number Theory"],
            topics: ["Prime Numbers"],
            subtopics: ["Smallest Primes"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "2",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "6",
          student: "student1",
          question: {
            _id: "q6",
            question: "Who wrote 'To Kill a Mockingbird'?",
            options: [
              { name: "Harper Lee", tag: "Correct", images: null, _id: "6_1" },
              {
                name: "Mark Twain",
                tag: "Incorrect",
                images: null,
                _id: "6_2",
              },
              {
                name: "J.K. Rowling",
                tag: "Incorrect",
                images: null,
                _id: "6_3",
              },
              {
                name: "Ernest Hemingway",
                tag: "Incorrect",
                images: null,
                _id: "6_4",
              },
            ],
            standard: 5,
            subject: "Literature",
            chapter: ["American Literature"],
            topics: ["Famous Authors"],
            subtopics: ["Books"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "Harper Lee",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
        {
          _id: "7",
          student: "student1",
          question: {
            _id: "q7",
            question: "What is the speed of light?",
            options: [
              {
                name: "300,000 km/s",
                tag: "Correct",
                images: null,
                _id: "7_1",
              },
              {
                name: "150,000 km/s",
                tag: "Incorrect",
                images: null,
                _id: "7_2",
              },
              {
                name: "450,000 km/s",
                tag: "Incorrect",
                images: null,
                _id: "7_3",
              },
              {
                name: "600,000 km/s",
                tag: "Incorrect",
                images: null,
                _id: "7_4",
              },
            ],
            standard: 5,
            subject: "Physics",
            chapter: ["Light"],
            topics: ["Speed of Light"],
            subtopics: ["Fundamental Constants"],
            level: "easy",
            images: [],
            createdBy: "teacher1",
            createdAt: "2023-01-01T00:00:00.000Z",
            __v: 0,
          },
          studentAnswer: "300,000 km/s",
          isCorrect: true,
          tag: "daily_quiz",
          createdAt: "2023-01-01T00:00:00.000Z",
          __v: 0,
        },
      ]}
    />
  );
};
export default page;
